///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KeePass_Assessment
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the KeePass_AssessmentRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a02d2631-cac4-472d-84fc-95875401a1e7")]
    public partial class KeePass_AssessmentRepository : RepoGenBaseFolder
    {
        static KeePass_AssessmentRepository instance = new KeePass_AssessmentRepository();
        KeePass_AssessmentRepositoryFolders.KeePass_AppAppFolder _keepass_app;
        KeePass_AssessmentRepositoryFolders.File_Sub_MenuAppFolder _file_sub_menu;
        KeePass_AssessmentRepositoryFolders.New_DB_Confirmation_PopUpAppFolder _new_db_confirmation_popup;
        KeePass_AssessmentRepositoryFolders.Create_New_DatabaseAppFolder _create_new_database;
        KeePass_AssessmentRepositoryFolders.Pwd_Creation_FormAppFolder _pwd_creation_form;
        KeePass_AssessmentRepositoryFolders.DB_Settings_FormAppFolder _db_settings_form;
        KeePass_AssessmentRepositoryFolders.New_Entry_FormAppFolder _new_entry_form;
        KeePass_AssessmentRepositoryFolders.Open_Database_FileAppFolder _open_database_file;
        KeePass_AssessmentRepositoryFolders.Master_Key_PopUpAppFolder _master_key_popup;

        /// <summary>
        /// Gets the singleton class instance representing the KeePass_AssessmentRepository element repository.
        /// </summary>
        [RepositoryFolder("a02d2631-cac4-472d-84fc-95875401a1e7")]
        public static KeePass_AssessmentRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public KeePass_AssessmentRepository() 
            : base("KeePass_AssessmentRepository", "/", null, 0, false, "a02d2631-cac4-472d-84fc-95875401a1e7", ".\\RepositoryImages\\KeePass_AssessmentRepositorya02d2631.rximgres")
        {
            _keepass_app = new KeePass_AssessmentRepositoryFolders.KeePass_AppAppFolder(this);
            _file_sub_menu = new KeePass_AssessmentRepositoryFolders.File_Sub_MenuAppFolder(this);
            _new_db_confirmation_popup = new KeePass_AssessmentRepositoryFolders.New_DB_Confirmation_PopUpAppFolder(this);
            _create_new_database = new KeePass_AssessmentRepositoryFolders.Create_New_DatabaseAppFolder(this);
            _pwd_creation_form = new KeePass_AssessmentRepositoryFolders.Pwd_Creation_FormAppFolder(this);
            _db_settings_form = new KeePass_AssessmentRepositoryFolders.DB_Settings_FormAppFolder(this);
            _new_entry_form = new KeePass_AssessmentRepositoryFolders.New_Entry_FormAppFolder(this);
            _open_database_file = new KeePass_AssessmentRepositoryFolders.Open_Database_FileAppFolder(this);
            _master_key_popup = new KeePass_AssessmentRepositoryFolders.Master_Key_PopUpAppFolder(this);
        }

#region Variables

        string _User_Entry = "My";

        /// <summary>
        /// Gets or sets the value of variable User_Entry.
        /// </summary>
        [TestVariable("ebbddaaf-724e-403e-a0ef-9ebe39ad4428")]
        public string User_Entry
        {
            get { return _User_Entry; }
            set { _User_Entry = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a02d2631-cac4-472d-84fc-95875401a1e7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeePass_App folder.
        /// </summary>
        [RepositoryFolder("cfb4dc76-378a-49ce-aa06-4195d462a4d0")]
        public virtual KeePass_AssessmentRepositoryFolders.KeePass_AppAppFolder KeePass_App
        {
            get { return _keepass_app; }
        }

        /// <summary>
        /// The File_Sub_Menu folder.
        /// </summary>
        [RepositoryFolder("fdd0fcfc-b03f-4097-b9f7-a7de897e647e")]
        public virtual KeePass_AssessmentRepositoryFolders.File_Sub_MenuAppFolder File_Sub_Menu
        {
            get { return _file_sub_menu; }
        }

        /// <summary>
        /// The New_DB_Confirmation_PopUp folder.
        /// </summary>
        [RepositoryFolder("e984521b-aca7-408d-805a-0c6f4a2036a0")]
        public virtual KeePass_AssessmentRepositoryFolders.New_DB_Confirmation_PopUpAppFolder New_DB_Confirmation_PopUp
        {
            get { return _new_db_confirmation_popup; }
        }

        /// <summary>
        /// The Create_New_Database folder.
        /// </summary>
        [RepositoryFolder("1f34496e-5cd2-4a37-a1f3-4451db53638c")]
        public virtual KeePass_AssessmentRepositoryFolders.Create_New_DatabaseAppFolder Create_New_Database
        {
            get { return _create_new_database; }
        }

        /// <summary>
        /// The Pwd_Creation_Form folder.
        /// </summary>
        [RepositoryFolder("0417149f-1958-4417-9387-9667be81de2b")]
        public virtual KeePass_AssessmentRepositoryFolders.Pwd_Creation_FormAppFolder Pwd_Creation_Form
        {
            get { return _pwd_creation_form; }
        }

        /// <summary>
        /// The DB_Settings_Form folder.
        /// </summary>
        [RepositoryFolder("4fdd544d-3f4b-4d68-b566-e6949876fbdb")]
        public virtual KeePass_AssessmentRepositoryFolders.DB_Settings_FormAppFolder DB_Settings_Form
        {
            get { return _db_settings_form; }
        }

        /// <summary>
        /// The New_Entry_Form folder.
        /// </summary>
        [RepositoryFolder("73e02b24-aa97-41c9-8dc6-dd3262c355c1")]
        public virtual KeePass_AssessmentRepositoryFolders.New_Entry_FormAppFolder New_Entry_Form
        {
            get { return _new_entry_form; }
        }

        /// <summary>
        /// The Open_Database_File folder.
        /// </summary>
        [RepositoryFolder("e0955624-65a4-4b5b-af99-e73a06e7acca")]
        public virtual KeePass_AssessmentRepositoryFolders.Open_Database_FileAppFolder Open_Database_File
        {
            get { return _open_database_file; }
        }

        /// <summary>
        /// The Master_Key_PopUp folder.
        /// </summary>
        [RepositoryFolder("56c7c1c4-22cc-4ee1-85a1-d3f1a6137405")]
        public virtual KeePass_AssessmentRepositoryFolders.Master_Key_PopUpAppFolder Master_Key_PopUp
        {
            get { return _master_key_popup; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class KeePass_AssessmentRepositoryFolders
    {
        /// <summary>
        /// The KeePass_AppAppFolder folder.
        /// </summary>
        [RepositoryFolder("cfb4dc76-378a-49ce-aa06-4195d462a4d0")]
        public partial class KeePass_AppAppFolder : RepoGenBaseFolder
        {
            KeePass_AssessmentRepositoryFolders.Menu_BarFolder _menu_bar;
            KeePass_AssessmentRepositoryFolders.Tool_BarFolder _tool_bar;
            KeePass_AssessmentRepositoryFolders.User_EntriesFolder _user_entries;

            /// <summary>
            /// Creates a new KeePass_App  folder.
            /// </summary>
            public KeePass_AppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass_App", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "cfb4dc76-378a-49ce-aa06-4195d462a4d0", "")
            {
                _menu_bar = new KeePass_AssessmentRepositoryFolders.Menu_BarFolder(this);
                _tool_bar = new KeePass_AssessmentRepositoryFolders.Tool_BarFolder(this);
                _user_entries = new KeePass_AssessmentRepositoryFolders.User_EntriesFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cfb4dc76-378a-49ce-aa06-4195d462a4d0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cfb4dc76-378a-49ce-aa06-4195d462a4d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Menu_Bar folder.
            /// </summary>
            [RepositoryFolder("d2fbacb9-d107-405b-bd47-05a226e33846")]
            public virtual KeePass_AssessmentRepositoryFolders.Menu_BarFolder Menu_Bar
            {
                get { return _menu_bar; }
            }

            /// <summary>
            /// The Tool_Bar folder.
            /// </summary>
            [RepositoryFolder("d7397834-a261-44e3-b71c-d9bacdfe3dea")]
            public virtual KeePass_AssessmentRepositoryFolders.Tool_BarFolder Tool_Bar
            {
                get { return _tool_bar; }
            }

            /// <summary>
            /// The User_Entries folder.
            /// </summary>
            [RepositoryFolder("0a026b39-d139-4009-b52a-ade152e3e4d1")]
            public virtual KeePass_AssessmentRepositoryFolders.User_EntriesFolder User_Entries
            {
                get { return _user_entries; }
            }
        }

        /// <summary>
        /// The Menu_BarFolder folder.
        /// </summary>
        [RepositoryFolder("d2fbacb9-d107-405b-bd47-05a226e33846")]
        public partial class Menu_BarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;

            /// <summary>
            /// Creates a new Menu_Bar  folder.
            /// </summary>
            public Menu_BarFolder(RepoGenBaseFolder parentFolder) :
                    base("Menu_Bar", "", parentFolder, 0, null, false, "d2fbacb9-d107-405b-bd47-05a226e33846", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "?/?/menuitem[@name='File']", "?/?/menuitem[@name='File']", 30000, null, "1b2a7d66-98c0-4544-80a3-0f0806a92f2e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d2fbacb9-d107-405b-bd47-05a226e33846")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("1b2a7d66-98c0-4544-80a3-0f0806a92f2e")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("1b2a7d66-98c0-4544-80a3-0f0806a92f2e")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }
        }

        /// <summary>
        /// The Tool_BarFolder folder.
        /// </summary>
        [RepositoryFolder("d7397834-a261-44e3-b71c-d9bacdfe3dea")]
        public partial class Tool_BarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_addentryInfo;

            /// <summary>
            /// Creates a new Tool_Bar  folder.
            /// </summary>
            public Tool_BarFolder(RepoGenBaseFolder parentFolder) :
                    base("Tool_Bar", "", parentFolder, 0, null, false, "d7397834-a261-44e3-b71c-d9bacdfe3dea", "")
            {
                _btn_addentryInfo = new RepoItemInfo(this, "Btn_AddEntry", "*/button[@name='Add Entry']", "?/?/button[@name='Add Entry']", 30000, null, "95e90cc4-ea0e-492f-bc6f-81e027bc93ec");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d7397834-a261-44e3-b71c-d9bacdfe3dea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_AddEntry item.
            /// </summary>
            [RepositoryItem("95e90cc4-ea0e-492f-bc6f-81e027bc93ec")]
            public virtual Ranorex.Button Btn_AddEntry
            {
                get
                {
                    return _btn_addentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("95e90cc4-ea0e-492f-bc6f-81e027bc93ec")]
            public virtual RepoItemInfo Btn_AddEntryInfo
            {
                get
                {
                    return _btn_addentryInfo;
                }
            }
        }

        /// <summary>
        /// The User_EntriesFolder folder.
        /// </summary>
        [RepositoryFolder("0a026b39-d139-4009-b52a-ade152e3e4d1")]
        public partial class User_EntriesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cell_userentryInfo;

            /// <summary>
            /// Creates a new User_Entries  folder.
            /// </summary>
            public User_EntriesFolder(RepoGenBaseFolder parentFolder) :
                    base("User_Entries", "", parentFolder, 0, null, false, "0a026b39-d139-4009-b52a-ade152e3e4d1", "")
            {
                _cell_userentryInfo = new RepoItemInfo(this, "Cell_UserEntry", ".//?//cell[@text=$User_Entry]", "", 30000, null, "22fbac8a-d7a3-498c-b558-d775d807c85f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a026b39-d139-4009-b52a-ade152e3e4d1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cell_UserEntry item.
            /// </summary>
            [RepositoryItem("22fbac8a-d7a3-498c-b558-d775d807c85f")]
            public virtual Ranorex.Cell Cell_UserEntry
            {
                get
                {
                    return _cell_userentryInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell_UserEntry item info.
            /// </summary>
            [RepositoryItemInfo("22fbac8a-d7a3-498c-b558-d775d807c85f")]
            public virtual RepoItemInfo Cell_UserEntryInfo
            {
                get
                {
                    return _cell_userentryInfo;
                }
            }
        }

        /// <summary>
        /// The File_Sub_MenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("fdd0fcfc-b03f-4097-b9f7-a7de897e647e")]
        public partial class File_Sub_MenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _openfileInfo;

            /// <summary>
            /// Creates a new File_Sub_Menu  folder.
            /// </summary>
            public File_Sub_MenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("File_Sub_Menu", "/contextmenu[@processname='KeePass']", parentFolder, 30000, null, true, "fdd0fcfc-b03f-4097-b9f7-a7de897e647e", "")
            {
                _newInfo = new RepoItemInfo(this, "New", "menuitem[@name='New...']", "menuitem[@name='New...']", 30000, null, "ccea2b9a-f6d9-4330-9a00-d7242acb42f1");
                _saveInfo = new RepoItemInfo(this, "Save", "menuitem[@name='Save']", "menuitem[@name='Save']", 30000, null, "ae122e50-b5c5-4291-b166-fac59927f967");
                _closeInfo = new RepoItemInfo(this, "Close", "menuitem[@name='Close']", "menuitem[@name='Close']", 30000, null, "52adccc5-c4b5-4f8f-a1cc-58a85d3544f0");
                _openInfo = new RepoItemInfo(this, "Open", "menuitem[@name='Open']", "menuitem[@name='Open']", 30000, null, "e7a72268-ecb8-45b9-80d0-919e597fad1a");
                _openfileInfo = new RepoItemInfo(this, "OpenFile", "menuitem[@name='Open File...']", "menuitem[@name='Open File...']", 30000, null, "15d41c1e-e7fb-46d1-9ad3-b0af69f184a3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fdd0fcfc-b03f-4097-b9f7-a7de897e647e")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fdd0fcfc-b03f-4097-b9f7-a7de897e647e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The New item.
            /// </summary>
            [RepositoryItem("ccea2b9a-f6d9-4330-9a00-d7242acb42f1")]
            public virtual Ranorex.MenuItem New
            {
                get
                {
                    return _newInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The New item info.
            /// </summary>
            [RepositoryItemInfo("ccea2b9a-f6d9-4330-9a00-d7242acb42f1")]
            public virtual RepoItemInfo NewInfo
            {
                get
                {
                    return _newInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("ae122e50-b5c5-4291-b166-fac59927f967")]
            public virtual Ranorex.MenuItem Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("ae122e50-b5c5-4291-b166-fac59927f967")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("52adccc5-c4b5-4f8f-a1cc-58a85d3544f0")]
            public virtual Ranorex.MenuItem Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("52adccc5-c4b5-4f8f-a1cc-58a85d3544f0")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("e7a72268-ecb8-45b9-80d0-919e597fad1a")]
            public virtual Ranorex.MenuItem Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("e7a72268-ecb8-45b9-80d0-919e597fad1a")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The OpenFile item.
            /// </summary>
            [RepositoryItem("15d41c1e-e7fb-46d1-9ad3-b0af69f184a3")]
            public virtual Ranorex.MenuItem OpenFile
            {
                get
                {
                    return _openfileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The OpenFile item info.
            /// </summary>
            [RepositoryItemInfo("15d41c1e-e7fb-46d1-9ad3-b0af69f184a3")]
            public virtual RepoItemInfo OpenFileInfo
            {
                get
                {
                    return _openfileInfo;
                }
            }
        }

        /// <summary>
        /// The New_DB_Confirmation_PopUpAppFolder folder.
        /// </summary>
        [RepositoryFolder("e984521b-aca7-408d-805a-0c6f4a2036a0")]
        public partial class New_DB_Confirmation_PopUpAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_okInfo;
            RepoItemInfo _btn_yesInfo;
            RepoItemInfo _btn_skipInfo;

            /// <summary>
            /// Creates a new New_DB_Confirmation_PopUp  folder.
            /// </summary>
            public New_DB_Confirmation_PopUpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("New_DB_Confirmation_PopUp", "/form[@title='KeePass']", parentFolder, 30000, null, true, "e984521b-aca7-408d-805a-0c6f4a2036a0", "")
            {
                _btn_okInfo = new RepoItemInfo(this, "Btn_OK", "*/?/?/button[@windowtext='OK']", "", 30000, null, "ba94e155-58d8-4fb4-9fe5-e242374fd2e6");
                _btn_yesInfo = new RepoItemInfo(this, "Btn_Yes", "button[@text='&Yes']", "button[@text='&Yes']", 30000, null, "90d2dbcf-ea30-47cd-b5f3-3974c37effd4");
                _btn_skipInfo = new RepoItemInfo(this, "Btn_Skip", "container[@class='DirectUIHWND']/?/?/button[@text='Skip']", ".//button[@text='Skip' and @class='Button']", 30000, null, "e1a0e68f-543a-4b0c-bd96-69317a2bab52");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e984521b-aca7-408d-805a-0c6f4a2036a0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e984521b-aca7-408d-805a-0c6f4a2036a0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_OK item.
            /// </summary>
            [RepositoryItem("ba94e155-58d8-4fb4-9fe5-e242374fd2e6")]
            public virtual Ranorex.Button Btn_OK
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_OK item info.
            /// </summary>
            [RepositoryItemInfo("ba94e155-58d8-4fb4-9fe5-e242374fd2e6")]
            public virtual RepoItemInfo Btn_OKInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }

            /// <summary>
            /// The Btn_Yes item.
            /// </summary>
            [RepositoryItem("90d2dbcf-ea30-47cd-b5f3-3974c37effd4")]
            public virtual Ranorex.Button Btn_Yes
            {
                get
                {
                    return _btn_yesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Yes item info.
            /// </summary>
            [RepositoryItemInfo("90d2dbcf-ea30-47cd-b5f3-3974c37effd4")]
            public virtual RepoItemInfo Btn_YesInfo
            {
                get
                {
                    return _btn_yesInfo;
                }
            }

            /// <summary>
            /// The Btn_Skip item.
            /// </summary>
            [RepositoryItem("e1a0e68f-543a-4b0c-bd96-69317a2bab52")]
            public virtual Ranorex.Button Btn_Skip
            {
                get
                {
                    return _btn_skipInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Skip item info.
            /// </summary>
            [RepositoryItemInfo("e1a0e68f-543a-4b0c-bd96-69317a2bab52")]
            public virtual RepoItemInfo Btn_SkipInfo
            {
                get
                {
                    return _btn_skipInfo;
                }
            }
        }

        /// <summary>
        /// The Create_New_DatabaseAppFolder folder.
        /// </summary>
        [RepositoryFolder("1f34496e-5cd2-4a37-a1f3-4451db53638c")]
        public partial class Create_New_DatabaseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfield_filenameInfo;
            RepoItemInfo _btn_saveInfo;

            /// <summary>
            /// Creates a new Create_New_Database  folder.
            /// </summary>
            public Create_New_DatabaseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Create_New_Database", "/form[@title='Create New Database']", parentFolder, 30000, null, true, "1f34496e-5cd2-4a37-a1f3-4451db53638c", "")
            {
                _txtfield_filenameInfo = new RepoItemInfo(this, "TxtField_FileName", "?//?/text[@accessiblename='File name:']", "", 30000, null, "7af22ae8-f15d-4cfb-bbe1-0a56eb6d79ff");
                _btn_saveInfo = new RepoItemInfo(this, "Btn_Save", "button[@text='&Save']", "button[@text='&Save']", 30000, null, "a60535a5-894f-4e9f-85fb-66524709211e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1f34496e-5cd2-4a37-a1f3-4451db53638c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1f34496e-5cd2-4a37-a1f3-4451db53638c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtField_FileName item.
            /// </summary>
            [RepositoryItem("7af22ae8-f15d-4cfb-bbe1-0a56eb6d79ff")]
            public virtual Ranorex.Text TxtField_FileName
            {
                get
                {
                    return _txtfield_filenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_FileName item info.
            /// </summary>
            [RepositoryItemInfo("7af22ae8-f15d-4cfb-bbe1-0a56eb6d79ff")]
            public virtual RepoItemInfo TxtField_FileNameInfo
            {
                get
                {
                    return _txtfield_filenameInfo;
                }
            }

            /// <summary>
            /// The Btn_Save item.
            /// </summary>
            [RepositoryItem("a60535a5-894f-4e9f-85fb-66524709211e")]
            public virtual Ranorex.Button Btn_Save
            {
                get
                {
                    return _btn_saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Save item info.
            /// </summary>
            [RepositoryItemInfo("a60535a5-894f-4e9f-85fb-66524709211e")]
            public virtual RepoItemInfo Btn_SaveInfo
            {
                get
                {
                    return _btn_saveInfo;
                }
            }
        }

        /// <summary>
        /// The Pwd_Creation_FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("0417149f-1958-4417-9387-9667be81de2b")]
        public partial class Pwd_Creation_FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfield_masterpwdInfo;
            RepoItemInfo _txtfiled_repeatpwdInfo;
            RepoItemInfo _btn_okInfo;

            /// <summary>
            /// Creates a new Pwd_Creation_Form  folder.
            /// </summary>
            public Pwd_Creation_FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Pwd_Creation_Form", "/form[@controlname='KeyCreationForm']", parentFolder, 30000, null, true, "0417149f-1958-4417-9387-9667be81de2b", "")
            {
                _txtfield_masterpwdInfo = new RepoItemInfo(this, "TxtField_MasterPwd", "text[@controlname='m_tbPassword']", "", 30000, null, "3ba9a919-9125-4b1b-b925-61c38e4be9d2");
                _txtfiled_repeatpwdInfo = new RepoItemInfo(this, "TxtFiled_RepeatPwd", ".//?//text[@accessiblename='Repeat password:']", "", 30000, null, "26df923a-c9a7-4c80-a987-e251379fbcf4");
                _btn_okInfo = new RepoItemInfo(this, "Btn_OK", "button[@controlname='m_btnOK']", "button[@controlname='m_btnOK']", 30000, null, "78b7b414-e65a-4335-a4d3-a9a8bc1e347a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0417149f-1958-4417-9387-9667be81de2b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0417149f-1958-4417-9387-9667be81de2b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtField_MasterPwd item.
            /// </summary>
            [RepositoryItem("3ba9a919-9125-4b1b-b925-61c38e4be9d2")]
            public virtual Ranorex.Text TxtField_MasterPwd
            {
                get
                {
                    return _txtfield_masterpwdInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_MasterPwd item info.
            /// </summary>
            [RepositoryItemInfo("3ba9a919-9125-4b1b-b925-61c38e4be9d2")]
            public virtual RepoItemInfo TxtField_MasterPwdInfo
            {
                get
                {
                    return _txtfield_masterpwdInfo;
                }
            }

            /// <summary>
            /// The TxtFiled_RepeatPwd item.
            /// </summary>
            [RepositoryItem("26df923a-c9a7-4c80-a987-e251379fbcf4")]
            public virtual Ranorex.Text TxtFiled_RepeatPwd
            {
                get
                {
                    return _txtfiled_repeatpwdInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtFiled_RepeatPwd item info.
            /// </summary>
            [RepositoryItemInfo("26df923a-c9a7-4c80-a987-e251379fbcf4")]
            public virtual RepoItemInfo TxtFiled_RepeatPwdInfo
            {
                get
                {
                    return _txtfiled_repeatpwdInfo;
                }
            }

            /// <summary>
            /// The Btn_OK item.
            /// </summary>
            [RepositoryItem("78b7b414-e65a-4335-a4d3-a9a8bc1e347a")]
            public virtual Ranorex.Button Btn_OK
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_OK item info.
            /// </summary>
            [RepositoryItemInfo("78b7b414-e65a-4335-a4d3-a9a8bc1e347a")]
            public virtual RepoItemInfo Btn_OKInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }
        }

        /// <summary>
        /// The DB_Settings_FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("4fdd544d-3f4b-4d68-b566-e6949876fbdb")]
        public partial class DB_Settings_FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_okInfo;

            /// <summary>
            /// Creates a new DB_Settings_Form  folder.
            /// </summary>
            public DB_Settings_FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DB_Settings_Form", "/form[@controlname='DatabaseSettingsForm']", parentFolder, 30000, null, true, "4fdd544d-3f4b-4d68-b566-e6949876fbdb", "")
            {
                _btn_okInfo = new RepoItemInfo(this, "Btn_OK", "button[@controlname='m_btnOK']", "button[@controlname='m_btnOK']", 30000, null, "f9548113-4020-4a8d-821a-5dd77bddec36");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4fdd544d-3f4b-4d68-b566-e6949876fbdb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4fdd544d-3f4b-4d68-b566-e6949876fbdb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_OK item.
            /// </summary>
            [RepositoryItem("f9548113-4020-4a8d-821a-5dd77bddec36")]
            public virtual Ranorex.Button Btn_OK
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_OK item info.
            /// </summary>
            [RepositoryItemInfo("f9548113-4020-4a8d-821a-5dd77bddec36")]
            public virtual RepoItemInfo Btn_OKInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }
        }

        /// <summary>
        /// The New_Entry_FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("73e02b24-aa97-41c9-8dc6-dd3262c355c1")]
        public partial class New_Entry_FormAppFolder : RepoGenBaseFolder
        {
            KeePass_AssessmentRepositoryFolders.Entry_FieldsFolder _entry_fields;
            RepoItemInfo _btn_okInfo;

            /// <summary>
            /// Creates a new New_Entry_Form  folder.
            /// </summary>
            public New_Entry_FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("New_Entry_Form", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, true, "73e02b24-aa97-41c9-8dc6-dd3262c355c1", "")
            {
                _entry_fields = new KeePass_AssessmentRepositoryFolders.Entry_FieldsFolder(this);
                _btn_okInfo = new RepoItemInfo(this, "Btn_OK", "button[@controlname='m_btnOK']", "button[@controlname='m_btnOK']", 30000, null, "4d2b3d4c-6594-4756-aebf-814cce13ef78");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73e02b24-aa97-41c9-8dc6-dd3262c355c1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73e02b24-aa97-41c9-8dc6-dd3262c355c1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_OK item.
            /// </summary>
            [RepositoryItem("4d2b3d4c-6594-4756-aebf-814cce13ef78")]
            public virtual Ranorex.Button Btn_OK
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_OK item info.
            /// </summary>
            [RepositoryItemInfo("4d2b3d4c-6594-4756-aebf-814cce13ef78")]
            public virtual RepoItemInfo Btn_OKInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }

            /// <summary>
            /// The Entry_Fields folder.
            /// </summary>
            [RepositoryFolder("fd6e47d5-25d4-4565-a260-bf56a376acc0")]
            public virtual KeePass_AssessmentRepositoryFolders.Entry_FieldsFolder Entry_Fields
            {
                get { return _entry_fields; }
            }
        }

        /// <summary>
        /// The Entry_FieldsFolder folder.
        /// </summary>
        [RepositoryFolder("fd6e47d5-25d4-4565-a260-bf56a376acc0")]
        public partial class Entry_FieldsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfield_passwordInfo;
            RepoItemInfo _txtfield_repeatInfo;
            RepoItemInfo _txtfield_titleInfo;
            RepoItemInfo _txtfield_usernameInfo;
            RepoItemInfo _txtfield_urlInfo;

            /// <summary>
            /// Creates a new Entry_Fields  folder.
            /// </summary>
            public Entry_FieldsFolder(RepoGenBaseFolder parentFolder) :
                    base("Entry_Fields", "?/?/tabpage[@controlname='m_tabEntry']", parentFolder, 30000, null, false, "fd6e47d5-25d4-4565-a260-bf56a376acc0", "")
            {
                _txtfield_passwordInfo = new RepoItemInfo(this, "TxtField_Password", "?/?/text[@accessiblename='Password:']", "", 30000, null, "ce820ee1-241e-4232-a2a4-9de86a78d19a");
                _txtfield_repeatInfo = new RepoItemInfo(this, "TxtField_Repeat", "?/?/text[@accessiblename='Repeat:']", "", 30000, null, "9fdf2916-2d85-4dbc-a8a3-d906d61ffcc6");
                _txtfield_titleInfo = new RepoItemInfo(this, "TxtField_Title", "?/?/text[@accessiblename='Title:']", "", 30000, null, "34894745-db17-4ba8-9d3a-a7f16b8600a2");
                _txtfield_usernameInfo = new RepoItemInfo(this, "TxtField_UserName", "?/?/text[@accessiblename='User name:']", "", 30000, null, "0305270e-7755-42a6-981b-3750f6db0cc5");
                _txtfield_urlInfo = new RepoItemInfo(this, "TxtField_URL", "?/?/text[@accessiblename='URL:']", "", 30000, null, "e186dc4b-c6fb-4af7-8083-397b2d191f6f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd6e47d5-25d4-4565-a260-bf56a376acc0")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd6e47d5-25d4-4565-a260-bf56a376acc0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtField_Password item.
            /// </summary>
            [RepositoryItem("ce820ee1-241e-4232-a2a4-9de86a78d19a")]
            public virtual Ranorex.Text TxtField_Password
            {
                get
                {
                    return _txtfield_passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_Password item info.
            /// </summary>
            [RepositoryItemInfo("ce820ee1-241e-4232-a2a4-9de86a78d19a")]
            public virtual RepoItemInfo TxtField_PasswordInfo
            {
                get
                {
                    return _txtfield_passwordInfo;
                }
            }

            /// <summary>
            /// The TxtField_Repeat item.
            /// </summary>
            [RepositoryItem("9fdf2916-2d85-4dbc-a8a3-d906d61ffcc6")]
            public virtual Ranorex.Text TxtField_Repeat
            {
                get
                {
                    return _txtfield_repeatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_Repeat item info.
            /// </summary>
            [RepositoryItemInfo("9fdf2916-2d85-4dbc-a8a3-d906d61ffcc6")]
            public virtual RepoItemInfo TxtField_RepeatInfo
            {
                get
                {
                    return _txtfield_repeatInfo;
                }
            }

            /// <summary>
            /// The TxtField_Title item.
            /// </summary>
            [RepositoryItem("34894745-db17-4ba8-9d3a-a7f16b8600a2")]
            public virtual Ranorex.Text TxtField_Title
            {
                get
                {
                    return _txtfield_titleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_Title item info.
            /// </summary>
            [RepositoryItemInfo("34894745-db17-4ba8-9d3a-a7f16b8600a2")]
            public virtual RepoItemInfo TxtField_TitleInfo
            {
                get
                {
                    return _txtfield_titleInfo;
                }
            }

            /// <summary>
            /// The TxtField_UserName item.
            /// </summary>
            [RepositoryItem("0305270e-7755-42a6-981b-3750f6db0cc5")]
            public virtual Ranorex.Text TxtField_UserName
            {
                get
                {
                    return _txtfield_usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_UserName item info.
            /// </summary>
            [RepositoryItemInfo("0305270e-7755-42a6-981b-3750f6db0cc5")]
            public virtual RepoItemInfo TxtField_UserNameInfo
            {
                get
                {
                    return _txtfield_usernameInfo;
                }
            }

            /// <summary>
            /// The TxtField_URL item.
            /// </summary>
            [RepositoryItem("e186dc4b-c6fb-4af7-8083-397b2d191f6f")]
            public virtual Ranorex.Text TxtField_URL
            {
                get
                {
                    return _txtfield_urlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_URL item info.
            /// </summary>
            [RepositoryItemInfo("e186dc4b-c6fb-4af7-8083-397b2d191f6f")]
            public virtual RepoItemInfo TxtField_URLInfo
            {
                get
                {
                    return _txtfield_urlInfo;
                }
            }
        }

        /// <summary>
        /// The Open_Database_FileAppFolder folder.
        /// </summary>
        [RepositoryFolder("e0955624-65a4-4b5b-af99-e73a06e7acca")]
        public partial class Open_Database_FileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfield_filenameInfo;
            RepoItemInfo _btn_openInfo;

            /// <summary>
            /// Creates a new Open_Database_File  folder.
            /// </summary>
            public Open_Database_FileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open_Database_File", "/form[@title='Open Database File']", parentFolder, 30000, null, true, "e0955624-65a4-4b5b-af99-e73a06e7acca", "")
            {
                _txtfield_filenameInfo = new RepoItemInfo(this, "TxtField_FileName", "?/?/text[@accessiblename='File name:']", "", 30000, null, "49b781da-d3b3-4911-a2de-a3b92e3ac130");
                _btn_openInfo = new RepoItemInfo(this, "Btn_Open", "button[@text='&Open']", "button[@text='&Open']", 30000, null, "d89a2464-7ed6-49df-880d-eb9c95c00162");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e0955624-65a4-4b5b-af99-e73a06e7acca")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0955624-65a4-4b5b-af99-e73a06e7acca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtField_FileName item.
            /// </summary>
            [RepositoryItem("49b781da-d3b3-4911-a2de-a3b92e3ac130")]
            public virtual Ranorex.Text TxtField_FileName
            {
                get
                {
                    return _txtfield_filenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_FileName item info.
            /// </summary>
            [RepositoryItemInfo("49b781da-d3b3-4911-a2de-a3b92e3ac130")]
            public virtual RepoItemInfo TxtField_FileNameInfo
            {
                get
                {
                    return _txtfield_filenameInfo;
                }
            }

            /// <summary>
            /// The Btn_Open item.
            /// </summary>
            [RepositoryItem("d89a2464-7ed6-49df-880d-eb9c95c00162")]
            public virtual Ranorex.Button Btn_Open
            {
                get
                {
                    return _btn_openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Open item info.
            /// </summary>
            [RepositoryItemInfo("d89a2464-7ed6-49df-880d-eb9c95c00162")]
            public virtual RepoItemInfo Btn_OpenInfo
            {
                get
                {
                    return _btn_openInfo;
                }
            }
        }

        /// <summary>
        /// The Master_Key_PopUpAppFolder folder.
        /// </summary>
        [RepositoryFolder("56c7c1c4-22cc-4ee1-85a1-d3f1a6137405")]
        public partial class Master_Key_PopUpAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_okInfo;
            RepoItemInfo _txt_pwdInfo;

            /// <summary>
            /// Creates a new Master_Key_PopUp  folder.
            /// </summary>
            public Master_Key_PopUpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Master_Key_PopUp", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "56c7c1c4-22cc-4ee1-85a1-d3f1a6137405", "")
            {
                _btn_okInfo = new RepoItemInfo(this, "Btn_OK", "button[@controlname='m_btnOK']", "button[@controlname='m_btnOK']", 30000, null, "146424f0-48b1-423f-90ec-a235b4d1f956");
                _txt_pwdInfo = new RepoItemInfo(this, "Txt_Pwd", "?/?/text[@accessiblerole='Text']", "", 30000, null, "1be103db-74a6-40c9-9daa-9cdfb311384e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("56c7c1c4-22cc-4ee1-85a1-d3f1a6137405")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("56c7c1c4-22cc-4ee1-85a1-d3f1a6137405")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_OK item.
            /// </summary>
            [RepositoryItem("146424f0-48b1-423f-90ec-a235b4d1f956")]
            public virtual Ranorex.Button Btn_OK
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_OK item info.
            /// </summary>
            [RepositoryItemInfo("146424f0-48b1-423f-90ec-a235b4d1f956")]
            public virtual RepoItemInfo Btn_OKInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }

            /// <summary>
            /// The Txt_Pwd item.
            /// </summary>
            [RepositoryItem("1be103db-74a6-40c9-9daa-9cdfb311384e")]
            public virtual Ranorex.Text Txt_Pwd
            {
                get
                {
                    return _txt_pwdInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Txt_Pwd item info.
            /// </summary>
            [RepositoryItemInfo("1be103db-74a6-40c9-9daa-9cdfb311384e")]
            public virtual RepoItemInfo Txt_PwdInfo
            {
                get
                {
                    return _txt_pwdInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
