///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePass_Assessment.Windows_File_Operations
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Enter_filename_and_Save_the_Database recording.
    /// </summary>
    [TestModule("8b1f5770-5859-4e10-baa4-e0f50ca22cfa", ModuleType.Recording, 1)]
    public partial class Enter_filename_and_Save_the_Database : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePass_Assessment.KeePass_AssessmentRepository repository.
        /// </summary>
        public static global::KeePass_Assessment.KeePass_AssessmentRepository repo = global::KeePass_Assessment.KeePass_AssessmentRepository.Instance;

        static Enter_filename_and_Save_the_Database instance = new Enter_filename_and_Save_the_Database();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Enter_filename_and_Save_the_Database()
        {
            FileName = "KeePass_Practice";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Enter_filename_and_Save_the_Database Instance
        {
            get { return instance; }
        }

#region Variables

        string _FileName;

        /// <summary>
        /// Gets or sets the value of variable FileName.
        /// </summary>
        [TestVariable("4815b337-65b4-4055-8fce-05c79cc0b4c4")]
        public string FileName
        {
            get { return _FileName; }
            set { _FileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Create_New_Database.TxtField_FileName' at Center.", repo.Create_New_Database.TxtField_FileNameInfo, new RecordItemIndex(0));
            repo.Create_New_Database.TxtField_FileName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Create_New_Database.TxtField_FileName'.", repo.Create_New_Database.TxtField_FileNameInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.Create_New_Database.TxtField_FileName);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'Create_New_Database.TxtField_FileName'.", repo.Create_New_Database.TxtField_FileNameInfo, new RecordItemIndex(2));
            repo.Create_New_Database.TxtField_FileName.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FileName' with focus on 'Create_New_Database.TxtField_FileName'.", repo.Create_New_Database.TxtField_FileNameInfo, new RecordItemIndex(3));
            repo.Create_New_Database.TxtField_FileName.PressKeys(FileName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Create_New_Database.Btn_Save' at Center.", repo.Create_New_Database.Btn_SaveInfo, new RecordItemIndex(4));
            repo.Create_New_Database.Btn_Save.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
