///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePass_Assessment.Windows_File_Operations
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_File recording.
    /// </summary>
    [TestModule("5b256aea-5626-45d7-9401-8bbcc884f908", ModuleType.Recording, 1)]
    public partial class Open_File : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePass_Assessment.KeePass_AssessmentRepository repository.
        /// </summary>
        public static global::KeePass_Assessment.KeePass_AssessmentRepository repo = global::KeePass_Assessment.KeePass_AssessmentRepository.Instance;

        static Open_File instance = new Open_File();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_File()
        {
            FileName = "KeePass_Practice";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_File Instance
        {
            get { return instance; }
        }

#region Variables

        string _FileName;

        /// <summary>
        /// Gets or sets the value of variable FileName.
        /// </summary>
        [TestVariable("9030eee2-a777-491b-b715-01c4584edd8e")]
        public string FileName
        {
            get { return _FileName; }
            set { _FileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass_App.Menu_Bar.File' at Center.", repo.KeePass_App.Menu_Bar.FileInfo, new RecordItemIndex(0));
            repo.KeePass_App.Menu_Bar.File.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'File_Sub_Menu.Open' at Center.", repo.File_Sub_Menu.OpenInfo, new RecordItemIndex(1));
            repo.File_Sub_Menu.Open.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'File_Sub_Menu.OpenFile' at Center.", repo.File_Sub_Menu.OpenFileInfo, new RecordItemIndex(2));
            repo.File_Sub_Menu.OpenFile.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open_Database_File.TxtField_FileName' at Center.", repo.Open_Database_File.TxtField_FileNameInfo, new RecordItemIndex(3));
            repo.Open_Database_File.TxtField_FileName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FileName' with focus on 'Open_Database_File.TxtField_FileName'.", repo.Open_Database_File.TxtField_FileNameInfo, new RecordItemIndex(4));
            repo.Open_Database_File.TxtField_FileName.PressKeys(FileName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open_Database_File.Btn_Open' at 50;17.", repo.Open_Database_File.Btn_OpenInfo, new RecordItemIndex(5));
            repo.Open_Database_File.Btn_Open.Click("50;17");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
