///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePass_Assessment.Master_Password
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Enter_Password recording.
    /// </summary>
    [TestModule("44bf0c99-9444-49ae-935e-f865eb8d9098", ModuleType.Recording, 1)]
    public partial class Enter_Password : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePass_Assessment.KeePass_AssessmentRepository repository.
        /// </summary>
        public static global::KeePass_Assessment.KeePass_AssessmentRepository repo = global::KeePass_Assessment.KeePass_AssessmentRepository.Instance;

        static Enter_Password instance = new Enter_Password();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Enter_Password()
        {
            Password = "TestPass123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Enter_Password Instance
        {
            get { return instance; }
        }

#region Variables

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("49aafe55-05aa-451f-83be-1c33e6a6adcb")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Master_Key_PopUp.Txt_Pwd' at 47;8.", repo.Master_Key_PopUp.Txt_PwdInfo, new RecordItemIndex(0));
            repo.Master_Key_PopUp.Txt_Pwd.Click("47;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'Master_Key_PopUp.Txt_Pwd'.", repo.Master_Key_PopUp.Txt_PwdInfo, new RecordItemIndex(1));
            repo.Master_Key_PopUp.Txt_Pwd.PressKeys(Password);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Master_Key_PopUp.Btn_OK' at 22;10.", repo.Master_Key_PopUp.Btn_OKInfo, new RecordItemIndex(2));
            repo.Master_Key_PopUp.Btn_OK.Click("22;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
