///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePass_Assessment.Master_Password
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Setup_New_Password_for_the_Database recording.
    /// </summary>
    [TestModule("5d9a9d72-df67-4b68-9fc0-3b752f9762cf", ModuleType.Recording, 1)]
    public partial class Setup_New_Password_for_the_Database : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePass_Assessment.KeePass_AssessmentRepository repository.
        /// </summary>
        public static global::KeePass_Assessment.KeePass_AssessmentRepository repo = global::KeePass_Assessment.KeePass_AssessmentRepository.Instance;

        static Setup_New_Password_for_the_Database instance = new Setup_New_Password_for_the_Database();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Setup_New_Password_for_the_Database()
        {
            Password = "TestPass123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Setup_New_Password_for_the_Database Instance
        {
            get { return instance; }
        }

#region Variables

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("14ee15a4-18d2-42d8-9931-623f5d7c4d04")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Pwd_Creation_Form.TxtField_MasterPwd' at Center.", repo.Pwd_Creation_Form.TxtField_MasterPwdInfo, new RecordItemIndex(0));
            repo.Pwd_Creation_Form.TxtField_MasterPwd.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'Pwd_Creation_Form.TxtField_MasterPwd'.", repo.Pwd_Creation_Form.TxtField_MasterPwdInfo, new RecordItemIndex(1));
            repo.Pwd_Creation_Form.TxtField_MasterPwd.PressKeys(Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Pwd_Creation_Form.TxtFiled_RepeatPwd' at Center.", repo.Pwd_Creation_Form.TxtFiled_RepeatPwdInfo, new RecordItemIndex(2));
            repo.Pwd_Creation_Form.TxtFiled_RepeatPwd.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'Pwd_Creation_Form.TxtFiled_RepeatPwd'.", repo.Pwd_Creation_Form.TxtFiled_RepeatPwdInfo, new RecordItemIndex(3));
            repo.Pwd_Creation_Form.TxtFiled_RepeatPwd.PressKeys(Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Pwd_Creation_Form.Btn_OK' at Center.", repo.Pwd_Creation_Form.Btn_OKInfo, new RecordItemIndex(4));
            repo.Pwd_Creation_Form.Btn_OK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'New_DB_Confirmation_PopUp.Btn_Yes' at Center.", repo.New_DB_Confirmation_PopUp.Btn_YesInfo, new RecordItemIndex(5));
            repo.New_DB_Confirmation_PopUp.Btn_Yes.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
