///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePass_Assessment.Entry
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NewEntry recording.
    /// </summary>
    [TestModule("8164318e-5bd1-4760-8415-410b1ad83361", ModuleType.Recording, 1)]
    public partial class NewEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePass_Assessment.KeePass_AssessmentRepository repository.
        /// </summary>
        public static global::KeePass_Assessment.KeePass_AssessmentRepository repo = global::KeePass_Assessment.KeePass_AssessmentRepository.Instance;

        static NewEntry instance = new NewEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NewEntry()
        {
            Title = "My";
            Username = "MyUser";
            Entry_Pwd = "AutoPass123";
            URL = "http://www.ranorex.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NewEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _Title;

        /// <summary>
        /// Gets or sets the value of variable Title.
        /// </summary>
        [TestVariable("e9243b3d-6571-4870-a436-930f9c6ef20c")]
        public string Title
        {
            get { return _Title; }
            set { _Title = value; }
        }

        string _Username;

        /// <summary>
        /// Gets or sets the value of variable Username.
        /// </summary>
        [TestVariable("d78a4cd5-5005-40c6-b2ae-abb2b74e71e2")]
        public string Username
        {
            get { return _Username; }
            set { _Username = value; }
        }

        string _Entry_Pwd;

        /// <summary>
        /// Gets or sets the value of variable Entry_Pwd.
        /// </summary>
        [TestVariable("c87b6169-ff02-402c-acc7-fb2d3ae02df6")]
        public string Entry_Pwd
        {
            get { return _Entry_Pwd; }
            set { _Entry_Pwd = value; }
        }

        string _URL;

        /// <summary>
        /// Gets or sets the value of variable URL.
        /// </summary>
        [TestVariable("67c2e665-030e-48ce-baf7-1f8508bcf69a")]
        public string URL
        {
            get { return _URL; }
            set { _URL = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable User_Entry.
        /// </summary>
        [TestVariable("ebbddaaf-724e-403e-a0ef-9ebe39ad4428")]
        public string User_Entry
        {
            get { return repo.User_Entry; }
            set { repo.User_Entry = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            createNewEntry(repo.New_Entry_Form.Entry_Fields.TxtField_TitleInfo, repo.New_Entry_Form.Entry_Fields.TxtField_UserNameInfo, repo.New_Entry_Form.Entry_Fields.TxtField_PasswordInfo, repo.New_Entry_Form.Entry_Fields.TxtField_RepeatInfo, repo.New_Entry_Form.Entry_Fields.TxtField_URLInfo, repo.New_Entry_Form.Btn_OKInfo, repo.KeePass_App.User_Entries.Cell_UserEntryInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
