///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KeePass_Assessment.Entry
{
    public partial class NewEntry
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void MergedUserCodeMethod1(RepoItemInfo textInfo, RepoItemInfo textInfo1, RepoItemInfo textInfo2, RepoItemInfo textInfo3, RepoItemInfo buttonInfo, RepoItemInfo cellInfo)
        {
            // TODO: Replace the following line with your code implementation.
            throw new NotImplementedException();
        }

        public void createNewEntry(RepoItemInfo textInfo, RepoItemInfo textInfo1, RepoItemInfo textInfo2, RepoItemInfo textInfo3, RepoItemInfo textInfo4, RepoItemInfo buttonInfo, RepoItemInfo cellInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo' at Center.", textInfo);
            textInfo.FindAdapter<Text>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Title' with focus on 'textInfo'.", textInfo);
            textInfo.FindAdapter<Text>().PressKeys(Title);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo1' at Center.", textInfo1);
            textInfo1.FindAdapter<Text>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Username' with focus on 'textInfo1'.", textInfo1);
            textInfo1.FindAdapter<Text>().PressKeys(Username);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo2' at Center.", textInfo2);
            textInfo2.FindAdapter<Text>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'textInfo2'.", textInfo2);
            Keyboard.PrepareFocus(textInfo2.FindAdapter<Text>());
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'textInfo2'.", textInfo2);
            textInfo2.FindAdapter<Text>().PressKeys("{Back}");
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Entry_Pwd' with focus on 'textInfo2'.", textInfo2);
            textInfo2.FindAdapter<Text>().PressKeys(Entry_Pwd);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo3' at Center.", textInfo3);
            textInfo3.FindAdapter<Text>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'textInfo3'.", textInfo3);
            Keyboard.PrepareFocus(textInfo3.FindAdapter<Text>());
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'textInfo3'.", textInfo3);
            textInfo3.FindAdapter<Text>().PressKeys("{Back}");
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Entry_Pwd' with focus on 'textInfo3'.", textInfo3);
            textInfo3.FindAdapter<Text>().PressKeys(Entry_Pwd);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo4' at Center.", textInfo4);
            textInfo4.FindAdapter<Text>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$URL' with focus on 'textInfo4'.", textInfo4);
            textInfo4.FindAdapter<Text>().PressKeys(URL);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at Center.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click();
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Title) on item 'cellInfo'.", cellInfo);
            Validate.AttributeEqual(cellInfo, "Text", Title);
        }

    }
}
