///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePass_Assessment.Entry
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_User_Entry recording.
    /// </summary>
    [TestModule("a27766c4-7522-4955-91a7-957f5404a378", ModuleType.Recording, 1)]
    public partial class Validate_User_Entry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePass_Assessment.KeePass_AssessmentRepository repository.
        /// </summary>
        public static global::KeePass_Assessment.KeePass_AssessmentRepository repo = global::KeePass_Assessment.KeePass_AssessmentRepository.Instance;

        static Validate_User_Entry instance = new Validate_User_Entry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_User_Entry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_User_Entry Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable User_Entry.
        /// </summary>
        [TestVariable("ebbddaaf-724e-403e-a0ef-9ebe39ad4428")]
        public string User_Entry
        {
            get { return repo.User_Entry; }
            set { repo.User_Entry = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'KeePass_App.User_Entries.Cell_UserEntry'.", repo.KeePass_App.User_Entries.Cell_UserEntryInfo, new RecordItemIndex(0));
            Validate.Exists(repo.KeePass_App.User_Entries.Cell_UserEntryInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
